ALTER USER "SA" SET PASSWORD 'YYYYY';
CREATE USER lofidrox PASSWORD 'XXXXX';

CREATE TABLE PUBLIC.PUBLIC.USERS (
	USERNAME VARCHAR(50),
	PWD VARCHAR(100),
	CONSTRAINT USERS_PK PRIMARY KEY (USERNAME)
);

CREATE TABLE PUBLIC.PUBLIC.FILES (
	ID INTEGER IDENTITY,
	NAME VARCHAR(512) NOT NULL,
	USERFROM VARCHAR(50),
	USERTO VARCHAR(50) NOT NULL,
	CONSTRAINT FILES_PK PRIMARY KEY (ID)
);

ALTER TABLE PUBLIC.PUBLIC.FILES ADD FILEPATH VARCHAR(4000) NOT NULL;
ALTER TABLE PUBLIC.PUBLIC.FILES DROP COLUMN FILEPATH;
ALTER TABLE PUBLIC.PUBLIC.FILES ADD FILEPATH VARCHAR(4000);
ALTER TABLE PUBLIC.PUBLIC.FILES ADD SENTBY VARCHAR(50);
ALTER TABLE PUBLIC.PUBLIC.FILES ADD SENTON TIMESTAMP;
ALTER TABLE PUBLIC.PUBLIC.FILES DROP COLUMN SENTBY;
ALTER TABLE PUBLIC.PUBLIC.FILES ADD DOWNLOADED BOOLEAN DEFAULT 0;

CREATE TABLE PUBLIC.PUBLIC.FILESDEST (
	ID INTEGER NOT NULL IDENTITY,
	FILEID INTEGER NOT NULL,
	USERTO VARCHAR(50) NOT NULL,
	DOWNLOADED BOOLEAN DEFAULT false,
	CONSTRAINT FILESDEST_PK PRIMARY KEY (ID)
);
ALTER TABLE PUBLIC.PUBLIC.FILES DROP COLUMN USERTO;
ALTER TABLE PUBLIC.PUBLIC.FILES DROP COLUMN DOWNLOADED;
ALTER TABLE PUBLIC.PUBLIC.FILES ADD DATATYPE VARCHAR(100);
ALTER TABLE PUBLIC.PUBLIC.FILES RENAME TO PUBLIC.PUBLIC.FILEDESCRIPTOR;
ALTER TABLE PUBLIC.PUBLIC.FILESDEST RENAME TO PUBLIC.PUBLIC.FILERECIPIENT;

GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE PUBLIC.PUBLIC.FILEDESCRIPTOR TO LOFIDROX;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE PUBLIC.PUBLIC.FILERECIPIENT TO LOFIDROX;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE PUBLIC.PUBLIC.USERS TO LOFIDROX;